### ISSUE TITLE
Perform trade study on various query language parsers to meet needs of proposed API Spec

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api-app#9]

**Comment by tloubrieu-jpl** [comment]
JavaCC (https://javacc.github.io/javacc/) is the most commonly used library (e.g by lucene).

There is a grammar definition (extended BMF ?) which could enable to re-use the grammar and generate parser in different languages.

These tools are mostly implemented in java/c++ because they are the basis for compilers.

We need some more options to complete the trade study.

**Comment by jordanpadams** [comment]
From @tdddblog, trade study completed at https://github.com/NASA-PDS/pdsen-search-service/blob/master/study/custom-query-language.md .

@tdddblog per the summary, do you have a conclusion about which technology you think we should pursue? additionally, can we move that markdown to this repo? I was thinking that pdsen-search-service repo was going to be more specific to our PDS.nasa.gov Search capabilities and then this PDS API App (combination of NASA-PDS/pds-api-server and NASA-PDS/pds-api-client) would contain the more generic PDS API software and design information. thoughts?
